<?php

function acf_banner()
{
    return array(
        array(
            'key' => 'field_6182f6e2311d4',
            'label' => 'Mass Times',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_6182f6f9311d5',
            'label' => 'Heading',
            'name' => 'banner_heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
			'key' => 'field_619e6495384ec',
			'label' => 'Background Color',
			'name' => 'banner_background_color',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'--clr-primary' => 'Primary',
				'--clr-secondary' => 'Secondary',
				'--clr-tertiary' => 'Tertiary',
				'--clr-quaternary' => 'Quaternary',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
        array(
            'key' => 'field_61a8f8226cbf0',
            'label' => 'Mass Times',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => null,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '*Mass Times can be set in <a href="/wp-admin/admin.php?page=theme-general-settings">Theme Settings > Theme Settings > Mass Times</a>',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_62434adb17370',
            'label' => 'Link',
            'name' => 'mass_times_link',
            'type' => 'link',
            'instructions' => '*Link to the full schedule',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_61a8f7aa6cbef',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
    );
}