<?php

function acf_featured_content()
{

    return array(
        array(
            'key' => 'field_6182f613311cf',
            'label' => 'Featured Content',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_6182f61f311d0',
            'label' => 'Featured Content Items',
            'name' => 'featured_content_items',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_6182f642311d1',
            'min' => 0,
            'max' => 4,
            'layout' => 'block',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_6182f642311d1',
                    'label' => 'Heading',
                    'name' => 'item_name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
					'key' => 'field_626818f2de636',
					'label' => 'Content',
					'name' => 'content',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => 150,
					'rows' => 4,
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_6182f61f311d0',
				),
                array(
					'key' => 'field_6182f6b9311d3',
					'label' => 'Icon',
					'name' => 'icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'fas',
						1 => 'far',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
					'parent_repeater' => 'field_6182f61f311d0',
				),
                array(
                    'key' => 'field_6196abe21f65f',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                ),
            ),
        ),
    );
}